clock = "$CLOCK"
static = true # always set CWD to the directory of this config

[options]
ROM = "rom.bin"
CLOCK = "1M"
NVRAM = "nvram0.img"
NVRAM_SIZE = "0x1000000"

[[region]]
type = "rom"
source = "$ROM"
match = 0xC000
match_mask = 0xC000
address_mask = 0x3FFF

[[region]]
type = "acia"
match = 0x9000
match_mask = 0xF000
address_mask = 0x0003

[[region]]
type = "ram"
size = 0x2
match = 0x8100
match_mask = 0xFF00
address_mask = 0x0001
name = "nvram_sector"

[[region]]
type = "ram"
nv = true
file = "$NVRAM"
size = "$NVRAM_SIZE"
match = 0x8200
match_mask = 0xFE00
address_mask = 0x01FF

banked = true
window_id_unused = 7
window_id_length = 7 # no window id
bank_id_length = 2 # bytes
control_area = "nvram_sector"

[[region]]
type = "ram"
size = 0x0100
match = 0x8000
match_mask = 0xFF00
address_mask = 0x00FF
name = "page_table"

[[region]]
type = "ram"
size = 0x1000000
match = 0x0000
match_mask = 0x8000
address_mask = 0x7FFF

banked = true
window_id_unused = 1 # 1 bit skipped
window_id_length = 8 # bits, including unused
bank_id_length = 2 # bytes
control_area = "page_table"
control_area_offset = 0