clock = "$CLOCK"
static = true

[options]
ROM = "wozmon.bin"
CLOCK = "1M"

[[region]]
type = "rom"
source = "$ROM"
match = 0xF000
match_mask = 0xF000
address_mask = 0x0FFF

[[region]]
type = "acia"
match = 0x9000
match_mask = 0xF000
address_mask = 0x0003
ocrcrlf = true

[[region]]
type = "ram"
size = 0x8000
match = 0x0000
match_mask = 0x8000
address_mask = 0x7FFF
